services:
  memstats-exporter:
    build: .
    container_name: memstats-exporter
    ports:
      - "9500:9500"
    volumes:
      - "/:/filesystem:ro"
      - "/proc:/host/proc:ro"
    restart: unless-stopped